# Generated by Django 5.2.16 on 2026-07-12 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinfo',
            old_name='users',
            new_name='user',
        ),
    ]
