services:
  - type: web
    name: calorycounter
    runtime: python

    buildCommand: "./build.sh"

    startCommand: "gunicorn CaloryCounter.wsgi:application"

    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: CaloryCounter.settings